routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['as' => 'page.'], function () {

    Route::get('/', [\App\Http\Controllers\IndexController::class, 'index'])->name('index');

    Route::group(['prefix' => 'uslugi', 'as' => 'services.'], function () {

        Route::get('/', [\App\Http\Controllers\ServiceController::class, 'all'])->name('all');
        Route::get('{category}/', [\App\Http\Controllers\ServiceCategoryController::class, 'index'])->name('category');
        Route::get('{category}/{service}/', [\App\Http\Controllers\ServiceController::class, 'index'])->name('service');
        Route::get(
            '{category}/{subcategory1}/{subcategory2}/{subcategory3?}/{subcategory4?}/',
            [\App\Http\Controllers\ServiceController::class, 'index']
        )->middleware([\App\Http\Middleware\ServiceMiddleware::class])->name('service.subcategory');

    });

    Route::group(['prefix' => 'advokaty', 'as' => 'persons.'], function () {

        Route::get('/', [\App\Http\Controllers\PersonController::class, 'all'])->name('all');
        Route::get('/{person}', [\App\Http\Controllers\PersonController::class, 'index'])->name('person');

    });

    Route::group(['prefix' => 'cases', 'as' => 'cases.'], function () {

        Route::get('/', [\App\Http\Controllers\CaseController::class, 'all'])->name('all');
        Route::get('/{case}/', [\App\Http\Controllers\CaseController::class, 'index'])->name('case');

    });

    Route::group(['prefix' => 'questions', 'as' => 'qa.'], function () {

        Route::get('/', [\App\Http\Controllers\QaController::class, 'all'])->name('all');
        Route::get('ajax', [\App\Http\Controllers\QaController::class, 'ajax'])->name('ajax');
        Route::get('/{qa}/', [\App\Http\Controllers\QaController::class, 'index'])->name('item');

    });

    Route::group(['prefix' => 'contacts', 'as' => 'contacts.'], function () {

        Route::get('/', [\App\Http\Controllers\ContactsController::class, 'index'])->name('index');

    });

    Route::group(['prefix' => 'journal', 'as' => 'posts.'], function () {

        Route::get('/', [\App\Http\Controllers\PostCategoryController::class, 'all'])->name('all');
        Route::get('tag/{tag}/', [\App\Http\Controllers\TagController::class, 'index'])->name('tag');
        Route::get('{category}/', [\App\Http\Controllers\PostCategoryController::class, 'index'])->name('category');
        Route::get('{category}/{post}', [\App\Http\Controllers\PostController::class, 'index'])->name('post');

    });

    Route::get('/about/', [\App\Http\Controllers\PageController::class, 'default'])->name('about');
    Route::get('/history/', [\App\Http\Controllers\PageController::class, 'default'])->name('officeHistory');

    Route::group(['prefix' => 'payment', 'as' => 'payment.'], function () {
        Route::get('pay', [\App\Http\Controllers\PaymentController::class, 'pay'])->name('pay');
    });
});

Route::group(['prefix' => 'modal', 'as' => 'modal.'], function () {

    Route::get('partner', [\App\Http\Controllers\PartnerController::class, 'modal'])->name('partner');

});

Route::group(['prefix' => 'blocks', 'as' => 'blocks.'], function () {

    Route::get('services/tab/{service}', [\App\Http\Controllers\ServiceController::class, 'tab'])->name('services.tab');
    Route::get('services/social', [\App\Http\Controllers\ServiceController::class, 'social'])->name('services.social');
    Route::get('services/{category?}', [\App\Http\Controllers\ServiceCategoryController::class, 'list'])->name('services');
    Route::get('services/related/{category}', [\App\Http\Controllers\ServiceCategoryController::class, 'related'])->name('services.related');
    Route::get('services/faq/{service}/{category}', [\App\Http\Controllers\FaqController::class, 'list'])->name('services.faq');
    Route::get('services/person/{person}', [\App\Http\Controllers\PersonController::class, 'big'])->name('services.person');
    Route::get('mentioning/{year?}', [\App\Http\Controllers\MentioningController::class, 'list'])->name('mentioning');
    Route::post('callback/store', [\App\Http\Controllers\CallbackController::class, 'store'])->name('callback.store');
    Route::get('thank/modal', [\App\Http\Controllers\ThankContoller::class, 'modal'])->name('thank.modal');
    Route::get('thank/carousel', [\App\Http\Controllers\ThankContoller::class, 'carousel'])->name('thank.carousel');
    Route::get('case/modal', [\App\Http\Controllers\CaseController::class, 'modal'])->name('case.modal');
    Route::get('help', [\App\Http\Controllers\ServiceController::class, 'help'])->name('help');
});

Route::group(['prefix' => 'comments', 'as' => 'comments.'], function () {
    Route::post('{post}/get', [\App\Http\Controllers\CommentController::class, 'get'])->name('get');
    Route::post('store', [\App\Http\Controllers\CommentController::class, 'store'])->name('store');
});

Route::get('yandex_130936c9dc22b6e7.html', function () {
    return view('pages.verification');
});

app/Models/Video.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Arr;
use Orchid\Filters\Filterable;
use Orchid\Screen\AsSource;

/**
 * Class Video
 * @package App\Models
 *
 * @property int $id
 * @property string $text
 * @property string $src
 * @property \Carbon\Carbon $createdAt
 * @property \Carbon\Carbon $updatedAt
 */
class Video extends Model
{
    use HasFactory;
    use AsSource;
    use Filterable;

    /**
     * @var string[]
     */
    protected $allowedFilters = [
        'id',
        'text',
        'created_at',
    ];

    /**
     * @var string[]
     */
    protected $allowedSorts = [
        'id',
        'text',
        'created_at',
    ];

    /**
     * @var array
     */
    protected $guarded = [];

    public function getPreviewAttribute() {
        $link = Arr::last(explode('/', $this->src));
        return "https://i3.ytimg.com/vi/$link/hqdefault.jpg";
    }
}

resources/views/partials/blocks/carousel/partner.blade.php
<div class="splide splide_white">
    <ul class="partner__carousel">
        @foreach($videos as $video)
            <li class="splide__slide w-full md:w-1/2 md:mr-6">
                <div class="splide__slide__container block partner__item">
                    <div class="relative flex">
                            <span data-url="{{ route('modal.partner', ['id' => $video->id]) }}"
                                  class="absolute top-0 right-0 bottom-0 left-0 cursor-pointer"
                                  data-partner data-id="{{ $video->id }}"></span>
                        <iframe width="560" height="315" data-src="{{ $video->src }}"
                                title="YouTube video player" frameborder="0"
                                allow="accelerometer; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                                allowfullscreen></iframe>
                    </div>
                </div>
            </li>
        @endforeach
    </ul>
    <div class="splide__arrows text-white mt-2">
        <button class="splide__arrow splide__arrow--prev">
            @include('partials.icons.arrow_rigth')
        </button>
        <button class="splide__arrow splide__arrow--next">
            @include('partials.icons.arrow_rigth')
        </button>
    </div>
</div>

resources/views/partials/blocks/carousel/persons.blade.php
<div class="splide splide_miniable ">
    <ul class="lg:mb-12 mt-6 list_unstyled persons__carousel">
        @foreach(\App\Models\Person::get()->sortBy('order') as $person)
            <li class="w-1/2 md:w-1/3 xl:w-1/5 splide__slide">
                @include('partials.blocks.persons.person_item')
            </li>
        @endforeach
    </ul>
    @if(\Agent::isMobile())
        <div class="splide__arrows text-primary mt-2 lg:hidden lg:mt-10">
            <button class="splide__arrow splide__arrow--prev">
                @include('partials.icons.arrow_rigth')
            </button>
            <button class="splide__arrow splide__arrow--next">
                @include('partials.icons.arrow_rigth')
            </button>
        </div>
    @endif
</div>

resources/views/partials/blocks/carousel/persons_small.blade.php
<div class="splide splide_miniable">
    <ul class="mb-6 list_unstyled persons__carousel persons__carousel_small">
        @foreach(\App\Models\Person::get()->sortBy('order') as $person)
            <li class="w-full md:w-1/2 xl:w-1/4">
                <a href="{{ route('page.persons.person', $person) }}"
                   class="splide__slide__container block text-center person">
                    <div class="person__image"
                         style="background-image:url('{{ $person->getFirstMediaUrl('face') }}');"></div>
                    <p class="font-semibold text-primary text-xl mb-1 person__name">
                        {{ $person->name }}
                    </p>
                    <p class="font-medium mb-1">
                        {{ $person->position }}
                    </p>
                    <p class="person__about whitespace-pre-line">{{ $person->about }}</p>
                </a>
            </li>
        @endforeach
    </ul>
    <div class="splide__arrows text-primary mt-2">
        <button class="splide__arrow splide__arrow--prev">
            @include('partials.icons.arrow_rigth')
        </button>
        <button class="splide__arrow splide__arrow--next">
            @include('partials.icons.arrow_rigth')
        </button>
    </div>
</div>

resources/views/partials/blocks/carousel/thanks.blade.php
<div>
    <ul class="list_unstyled mb-2 thanks__carousel" @if($ajax ?? true) data-url="{{ route('blocks.thank.carousel') }}" @endif>
        @include('partials.blocks.carousel.thanks_inner', ['thanks' => $thanks->take($count)])
    </ul>
    <div class="splide__arrows text-primary mt-2">
        <button class="splide__arrow splide__arrow--prev">
            @include('partials.icons.arrow_rigth')
        </button>
        <button class="splide__arrow splide__arrow--next">
            @include('partials.icons.arrow_rigth')
        </button>
    </div>
</div>

resources/views/partials/blocks/carousel/thanks_inner.blade.php
@foreach($thanks as $thank)
    <li class="w-full md:w-1/2 md:px-4">
        <div class="splide__slide__container block thank">
            <div class="bg-white px-4 py-6">
                <h5 class="mt-2 font-semibold text-primary text-2xl" data-id="{{ $thank->id }}"
                    data-url="{{ route('blocks.thank.modal', ['id' => $thank->id ]) }}">
                    {{ $thank->name ?? '' }}
                </h5>
                @if($thank->service)
                    <p class="mb-2">
                                    <span class="text-sm text-grey-400">{{ __('blocks.thanks.service') }}
                                        <a
                                           class="text-primary border-b border-primary">
                                            {{ $thank->service->name ?? '' }}
                                        </a>
                                    </span>
                    </p>
                @endif
                <p class="font-medium thank__text" data-id="{{ $thank->id }}"
                   data-url="{{ route('blocks.thank.modal', ['id' => $thank->id ]) }}">{!! $thank->body !!}</p>
            </div>
        </div>
    </li>
@endforeach

resources/views/partials/blocks/carousel/videos.blade.php
<div class="splide splide_white">
    <ul class="partner__carousel _custom">
        @foreach($videos as $video)
            <li class="splide__slide w-full md:w-1/3 md:mr-6">
                <div class="splide__slide__container block partner__item">
                    <div class="relative flex">
                        <span data-url="{{ route('modal.partner', ['id' => $video->id]) }}"
                              class="absolute top-0 right-0 bottom-0 left-0 cursor-pointer"
                              data-partner data-id="{{ $video->id }}"></span>
                        {{--                        <iframe width="560" height="315" data-src="{{ $video->src }}"--}}
                        {{--                                title="YouTube video player" frameborder="0"--}}
                        {{--                                allow="accelerometer; clipboard-write; encrypted-media; gyroscope; picture-in-picture"--}}
                        {{--                                allowfullscreen></iframe>--}}
                        <img class="_img" src="{{ $video->preview }}">
                        <p class="partner__item__title">
                            {{ $video->title ?? '' }}
                        </p>
                        <div class="partner__item__source">
                            <img src="/img/logo_square 1.png" alt="Moment istiny">
                            <span class="partner__item__source__name">{{ __('pages.service.long.social.source.name') }}</span>
                        </div>
                    </div>
                </div>
            </li>
        @endforeach
    </ul>
    <div class="splide__arrows text-white mt-2">
        <button class="splide__arrow splide__arrow--prev">
            @include('partials.icons.arrow_rigth')
        </button>
        <button class="splide__arrow splide__arrow--next">
            @include('partials.icons.arrow_rigth')
        </button>
    </div>
</div>