routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['as' => 'page.'], function () {

    Route::get('/', [\App\Http\Controllers\IndexController::class, 'index'])->name('index');

    Route::group(['prefix' => 'uslugi', 'as' => 'services.'], function () {

        Route::get('/', [\App\Http\Controllers\ServiceController::class, 'all'])->name('all');
        Route::get('{category}/', [\App\Http\Controllers\ServiceCategoryController::class, 'index'])->name('category');
        Route::get('{category}/{service}/', [\App\Http\Controllers\ServiceController::class, 'index'])->name('service');
        Route::get(
            '{category}/{subcategory1}/{subcategory2}/{subcategory3?}/{subcategory4?}/',
            [\App\Http\Controllers\ServiceController::class, 'index']
        )->middleware([\App\Http\Middleware\ServiceMiddleware::class])->name('service.subcategory');

    });

    Route::group(['prefix' => 'advokaty', 'as' => 'persons.'], function () {

        Route::get('/', [\App\Http\Controllers\PersonController::class, 'all'])->name('all');
        Route::get('/{person}', [\App\Http\Controllers\PersonController::class, 'index'])->name('person');

    });

    Route::group(['prefix' => 'cases', 'as' => 'cases.'], function () {

        Route::get('/', [\App\Http\Controllers\CaseController::class, 'all'])->name('all');
        Route::get('/{case}/', [\App\Http\Controllers\CaseController::class, 'index'])->name('case');

    });

    Route::group(['prefix' => 'questions', 'as' => 'qa.'], function () {

        Route::get('/', [\App\Http\Controllers\QaController::class, 'all'])->name('all');
        Route::get('ajax', [\App\Http\Controllers\QaController::class, 'ajax'])->name('ajax');
        Route::get('/{qa}/', [\App\Http\Controllers\QaController::class, 'index'])->name('item');

    });

    Route::group(['prefix' => 'contacts', 'as' => 'contacts.'], function () {

        Route::get('/', [\App\Http\Controllers\ContactsController::class, 'index'])->name('index');

    });

    Route::group(['prefix' => 'journal', 'as' => 'posts.'], function () {

        Route::get('/', [\App\Http\Controllers\PostCategoryController::class, 'all'])->name('all');
        Route::get('tag/{tag}/', [\App\Http\Controllers\TagController::class, 'index'])->name('tag');
        Route::get('{category}/', [\App\Http\Controllers\PostCategoryController::class, 'index'])->name('category');
        Route::get('{category}/{post}', [\App\Http\Controllers\PostController::class, 'index'])->name('post');

    });

    Route::get('/about/', [\App\Http\Controllers\PageController::class, 'default'])->name('about');
    Route::get('/history/', [\App\Http\Controllers\PageController::class, 'default'])->name('officeHistory');

    Route::group(['prefix' => 'payment', 'as' => 'payment.'], function () {
        Route::get('pay', [\App\Http\Controllers\PaymentController::class, 'pay'])->name('pay');
    });
});

Route::group(['prefix' => 'modal', 'as' => 'modal.'], function () {

    Route::get('partner', [\App\Http\Controllers\PartnerController::class, 'modal'])->name('partner');

});

Route::group(['prefix' => 'blocks', 'as' => 'blocks.'], function () {

    Route::get('services/tab/{service}', [\App\Http\Controllers\ServiceController::class, 'tab'])->name('services.tab');
    Route::get('services/social', [\App\Http\Controllers\ServiceController::class, 'social'])->name('services.social');
    Route::get('services/{category?}', [\App\Http\Controllers\ServiceCategoryController::class, 'list'])->name('services');
    Route::get('services/related/{category}', [\App\Http\Controllers\ServiceCategoryController::class, 'related'])->name('services.related');
    Route::get('services/faq/{service}/{category}', [\App\Http\Controllers\FaqController::class, 'list'])->name('services.faq');
    Route::get('services/person/{person}', [\App\Http\Controllers\PersonController::class, 'big'])->name('services.person');
    Route::get('mentioning/{year?}', [\App\Http\Controllers\MentioningController::class, 'list'])->name('mentioning');
    Route::post('callback/store', [\App\Http\Controllers\CallbackController::class, 'store'])->name('callback.store');
    Route::get('thank/modal', [\App\Http\Controllers\ThankContoller::class, 'modal'])->name('thank.modal');
    Route::get('thank/carousel', [\App\Http\Controllers\ThankContoller::class, 'carousel'])->name('thank.carousel');
    Route::get('case/modal', [\App\Http\Controllers\CaseController::class, 'modal'])->name('case.modal');
    Route::get('help', [\App\Http\Controllers\ServiceController::class, 'help'])->name('help');
});

Route::group(['prefix' => 'comments', 'as' => 'comments.'], function () {
    Route::post('{post}/get', [\App\Http\Controllers\CommentController::class, 'get'])->name('get');
    Route::post('store', [\App\Http\Controllers\CommentController::class, 'store'])->name('store');
});

Route::get('yandex_130936c9dc22b6e7.html', function () {
    return view('pages.verification');
});

app/Models/Post.php
<?php

namespace App\Models;

use App\Services\HasMetricsInterface;
use App\Services\Metricable;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Orchid\Filters\Filterable;
use Orchid\Screen\AsSource;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;

/**
 * Class Post
 * @package App\Models
 *
 * @property int $id
 * @property string $name
 * @property string $slug
 * @property int $author_id
 * @property int $status_id
 * @property array $data
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 *
 * @property Page $page
 * @property \App\Models\PostCategory[]|\Illuminate\Support\Collection $categories
 * @property \App\Models\Comment[]|\Illuminate\Support\Collection $comments
 * @property \App\Models\Tag[]|\Illuminate\Support\Collection $tags
 * @property \App\Models\PostCategory $category
 * @property \App\Models\Person $author
 */
class Post extends Model implements HasMedia, HasMetricsInterface
{
    use HasFactory;
    use InteractsWithMedia;
    use AsSource;
    use Filterable;
    use Metricable;

    const STATUS_PUBLISHED = 1,
        STATUS_DRAFT = 2,
        STATUS_DISABLED = 3;

    /**
     * @var string[]
     */
    protected $allowedFilters = [
        'id',
        'name',
        'slug',
        'created_at',
    ];

    /**
     * @var string[]
     */
    protected $allowedSorts = [
        'id',
        'name',
        'slug',
        'created_at',
    ];

    /**
     * @var array
     */
    protected $guarded = [];

    /**
     * @var string[]
     */
    protected $casts = [
        'data' => 'array',
    ];

    protected $with = [
        'author',
        'tags',
        'comments',
    ];

    /**
     * @return string
     */
    public function getRouteKeyName()
    {
        if (request()->routeIs('platform.*'))
            return 'id';
        return 'slug';
    }

    protected static function boot()
    {
        parent::boot();
        static::addGlobalScope('active', function (Builder $builder) {
            if (!request()->routeIs('platform.*'))
                $builder->where('status_id', self::STATUS_PUBLISHED);
        });
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\MorphOne
     */
    public function page(): \Illuminate\Database\Eloquent\Relations\MorphOne
    {
        return $this->morphOne(Page::class, 'pageable');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function author(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(Person::class, 'author_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function categories(): \Illuminate\Database\Eloquent\Relations\BelongsToMany
    {
        return $this->belongsToMany(PostCategory::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\MorphMany
     */
    public function comments()
    {
        return $this->morphMany(Comment::class, 'commentable');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function tags(): \Illuminate\Database\Eloquent\Relations\BelongsToMany
    {
        return $this->belongsToMany(Tag::class);
    }

    /**
     * @return \App\Models\PostCategory|null
     */
    public function getCategoryAttribute(): ?PostCategory
    {
        return $this->categories()->first();
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function persons(): \Illuminate\Database\Eloquent\Relations\BelongsToMany {
        return $this->belongsToMany(Person::class, 'persons_posts');
    }

    /**
     * @return string
     */
    public function getLink(): string
    {
        return route('page.posts.post', [
            'category' => $this->category->slug ?? '',
            'post' => $this->slug ?? '',
        ]);
    }

    /**
     * @return string
     */
    public function image(): string
    {
        $image = $this->getFirstMediaUrl('image');
        if ($image)
            return $image;
        if ($this->category)
            return $this->category->getFirstMediaUrl('image');
        return '';
    }
}

resources/views/partials/blocks/maps/map.blade.php
@if(count($data) > 0)
    <p class="font-semibold">{{ __('blocks.map.title') }}</p>
    <ul class="list_unstyled block__map">
        @foreach($data as $i => $block)
            <li>
                <a href="#block-{{ $i }}">
                    {!! $block['data']['text'] !!}
                </a>
            </li>
        @endforeach
    </ul>
@endif

resources/views/partials/blocks/maps/map_service.blade.php
<section class="page_service_long__contacts__wrap">
    <div class="page_service_long__contacts__map">
        <div id="map" style="height: 100%;width: 100%;"></div>
        {{--        <iframe src="https://yandex.ru/map-widget/v1/?um=constructor%3A315e44a933f8f2cfde66cb82a7bdbe80f04d477e40c11eea7f20dff0da8162a6&amp;source=constructor"--}}
        {{--                width="100%" height="100%" frameborder="0"></iframe>--}}
    </div>
    <div class="container">
        <div class="page_service_long__contacts">
            <h3 class="page_service_long__contacts__title">
                {{ __('pages.contacts.title') }}
            </h3>

            <div class="page_service_long__contacts__item">
                <p class="page_service_long__contacts__item__title">
                    {{ __('pages.contacts.address') }}
                </p>
                <p class="page_service_long__contacts__item__text">
                    {{ \Settings::get('address') }}
                </p>
            </div>

            <div class="page_service_long__contacts__item">
                <p class="page_service_long__contacts__item__title">
                    {{ __('pages.contacts.work_time') }}
                </p>
                <p class="page_service_long__contacts__item__text">
                    {{ \Settings::get('work_time') }}
                </p>
            </div>

            <div class="page_service_long__contacts__item page_service_long__contacts__item__social">
                <div>
                    <p class="page_service_long__contacts__item__title">
                        {{ __('pages.service.long.contacts.phones') }}
                    </p>
                    <p class="page_service_long__contacts__item__text">
                        <a href="tel:{{ \Settings::getPhoneLink('phone_1') }}">
                            {{ \Settings::get('phone_1') }}
                        </a>
                        <a href="tel:{{ \Settings::getPhoneLink('phone_2') }}">
                            {{ \Settings::get('phone_2') }}
                        </a>
                        <a href="mailto:{{ \Settings::get('email') }}">
                            {{ \Settings::get('email') }}
                        </a>
                    </p>
                </div>
                <div class="page_service_long__contacts__item__r">
                    <a href="{{ \Settings::get('telegram') }}"
                       target="_blank" class="_telegram">
                        @include('partials.icons.telegram')
                    </a>
                    <a href="{{ \Settings::get('whatsapp') }}"
                       target="_blank" class="_whatsapp">
                        @include('partials.icons.whatsapp')
                    </a>
                </div>
            </div>

            <a class="btn btn_main page_service_long__contacts__link modal-callback-open">
                {{ __('pages.service.long.contacts.link') }}
            </a>

        </div>
    </div>
</section>

<script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU&amp;apikey=534cb9cd-da65-4e29-bc9c-0e8d118acbe6"
        type="text/javascript"></script>
<script>
    ymaps.ready(function () {
        var zoomControl = new ymaps.control.ZoomControl();
        // var routeControl = new ymaps.control.RoutePanel({options: {position: {right: 5, top: 5}, autofocus: false}});

        var myMap = new ymaps.Map('map', {
              center: [55.742977, 37.670176],
              zoom: 17,
              controls: [zoomControl],
          }, {
              searchControlProvider: 'yandex#search'
          }),

          // Создаём макет содержимого.
          MyIconContentLayout = ymaps.templateLayoutFactory.createClass(
            '<div style="color: #FFFFFF; font-weight: bold;">$[properties.iconContent]</div>'
          ),

          myPlacemark = new ymaps.Placemark([55.743036, 37.671346], {
              hintContent: '',
              balloonContent: '',
              iconContent: ''
          }, {
              // Опции.
              // Необходимо указать данный тип макета.
              iconLayout: 'default#imageWithContent',
              // Своё изображение иконки метки.
              iconImageHref: '/img/map_icon_alt.png',
              // Размеры метки.
              iconImageSize: [48, 72],
              // Смещение левого верхнего угла иконки относительно
              // её "ножки" (точки привязки).
              iconImageOffset: [-24, -72],
              // Смещение слоя с содержимым относительно слоя с картинкой.
              iconContentOffset: [15, 15],
              // Макет содержимого.
              iconContentLayout: MyIconContentLayout
          });

        myMap.behaviors.disable('scrollZoom');
        myMap.controls.remove();

        myMap.geoObjects
          .add(myPlacemark);

        // routeControl.routePanel.state.set({
        //     from: "метро Площадь Ильича",
        //     to: "Большая Андроньевская улица, 13с2",
        // });
        //
        // myMap.setCenter([55.742977, 37.670176], 17, {
        //     checkZoomRange: true
        // });
        //
        // var location = ymaps.geolocation.get();
        //
        // location.then(function (res) {
        //     var userTextLocation = res.geoObjects.get(0).properties.get('text');
        //     routeControl.routePanel.state.set({
        //         from: userTextLocation,
        //         to: 'Большая Андроньевская улица, 13с2'
        //     });
        //
        //     setTimeout(function () {
        //         myMap.setCenter([55.742977, 37.670176], 17, {
        //             // checkZoomRange: true
        //         });
        //     }, 5000);
        // });

    });
</script>