routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['as' => 'page.'], function () {

    Route::get('/', [\App\Http\Controllers\IndexController::class, 'index'])->name('index');

    Route::group(['prefix' => 'uslugi', 'as' => 'services.'], function () {

        Route::get('/', [\App\Http\Controllers\ServiceController::class, 'all'])->name('all');
        Route::get('{category}/', [\App\Http\Controllers\ServiceCategoryController::class, 'index'])->name('category');
        Route::get('{category}/{service}/', [\App\Http\Controllers\ServiceController::class, 'index'])->name('service');
        Route::get(
            '{category}/{subcategory1}/{subcategory2}/{subcategory3?}/{subcategory4?}/',
            [\App\Http\Controllers\ServiceController::class, 'index']
        )->middleware([\App\Http\Middleware\ServiceMiddleware::class])->name('service.subcategory');

    });

    Route::group(['prefix' => 'advokaty', 'as' => 'persons.'], function () {

        Route::get('/', [\App\Http\Controllers\PersonController::class, 'all'])->name('all');
        Route::get('/{person}', [\App\Http\Controllers\PersonController::class, 'index'])->name('person');

    });

    Route::group(['prefix' => 'cases', 'as' => 'cases.'], function () {

        Route::get('/', [\App\Http\Controllers\CaseController::class, 'all'])->name('all');
        Route::get('/{case}/', [\App\Http\Controllers\CaseController::class, 'index'])->name('case');

    });

    Route::group(['prefix' => 'questions', 'as' => 'qa.'], function () {

        Route::get('/', [\App\Http\Controllers\QaController::class, 'all'])->name('all');
        Route::get('ajax', [\App\Http\Controllers\QaController::class, 'ajax'])->name('ajax');
        Route::get('/{qa}/', [\App\Http\Controllers\QaController::class, 'index'])->name('item');

    });

    Route::group(['prefix' => 'contacts', 'as' => 'contacts.'], function () {

        Route::get('/', [\App\Http\Controllers\ContactsController::class, 'index'])->name('index');

    });

    Route::group(['prefix' => 'journal', 'as' => 'posts.'], function () {

        Route::get('/', [\App\Http\Controllers\PostCategoryController::class, 'all'])->name('all');
        Route::get('tag/{tag}/', [\App\Http\Controllers\TagController::class, 'index'])->name('tag');
        Route::get('{category}/', [\App\Http\Controllers\PostCategoryController::class, 'index'])->name('category');
        Route::get('{category}/{post}', [\App\Http\Controllers\PostController::class, 'index'])->name('post');

    });

    Route::get('/about/', [\App\Http\Controllers\PageController::class, 'default'])->name('about');
    Route::get('/history/', [\App\Http\Controllers\PageController::class, 'default'])->name('officeHistory');

    Route::group(['prefix' => 'payment', 'as' => 'payment.'], function () {
        Route::get('pay', [\App\Http\Controllers\PaymentController::class, 'pay'])->name('pay');
    });
});

Route::group(['prefix' => 'modal', 'as' => 'modal.'], function () {

    Route::get('partner', [\App\Http\Controllers\PartnerController::class, 'modal'])->name('partner');

});

Route::group(['prefix' => 'blocks', 'as' => 'blocks.'], function () {

    Route::get('services/tab/{service}', [\App\Http\Controllers\ServiceController::class, 'tab'])->name('services.tab');
    Route::get('services/social', [\App\Http\Controllers\ServiceController::class, 'social'])->name('services.social');
    Route::get('services/{category?}', [\App\Http\Controllers\ServiceCategoryController::class, 'list'])->name('services');
    Route::get('services/related/{category}', [\App\Http\Controllers\ServiceCategoryController::class, 'related'])->name('services.related');
    Route::get('services/faq/{service}/{category}', [\App\Http\Controllers\FaqController::class, 'list'])->name('services.faq');
    Route::get('services/person/{person}', [\App\Http\Controllers\PersonController::class, 'big'])->name('services.person');
    Route::get('mentioning/{year?}', [\App\Http\Controllers\MentioningController::class, 'list'])->name('mentioning');
    Route::post('callback/store', [\App\Http\Controllers\CallbackController::class, 'store'])->name('callback.store');
    Route::get('thank/modal', [\App\Http\Controllers\ThankContoller::class, 'modal'])->name('thank.modal');
    Route::get('thank/carousel', [\App\Http\Controllers\ThankContoller::class, 'carousel'])->name('thank.carousel');
    Route::get('case/modal', [\App\Http\Controllers\CaseController::class, 'modal'])->name('case.modal');
    Route::get('help', [\App\Http\Controllers\ServiceController::class, 'help'])->name('help');
});

Route::group(['prefix' => 'comments', 'as' => 'comments.'], function () {
    Route::post('{post}/get', [\App\Http\Controllers\CommentController::class, 'get'])->name('get');
    Route::post('store', [\App\Http\Controllers\CommentController::class, 'store'])->name('store');
});

Route::get('yandex_130936c9dc22b6e7.html', function () {
    return view('pages.verification');
});

resources/views/pages/case.blade.php
@extends('partials.body')

@section('content')
    <div class="container container_small">
        @include('partials.blocks.breadcrumbs.breadcrumbs')
    </div>

    <div class="container container_small">
        <div class="page__inner page_case">
            @if(\Auth::user() && \Auth::user()->hasAccess('platform.index'))
                <section class="container container_small bg-white mx-auto">
                    <div class="flex justify-end">
                        <a href="{{ route('platform.casepages.edit', $case->id) }}" class="btn btn_admin btn_sm">Редактировать</a>
                    </div>
                </section>
            @endif

            <h1 class="text-primary">
                {{ $case->name }}
            </h1>
            @include('partials.blocks.author.author', ['author' => $case->person, 'post' => $case])

            <table class="page__cases__case__properties page_case__properties">
                @foreach(__('pages.case_page.properties') as $key => $name)
                    <tr>
                        <td class="page__cases__case__properties__name">
                            {{ $name }}
                        </td>
                        <td class="page__cases__case__properties__value">
                            @isset($case->properties[$key])
                                {{ $case->properties[$key] }}
                            @endisset
                        </td>
                    </tr>
                @endforeach
                <tr>
                    <td class="page__cases__case__properties__name">
                        {{ __('pages.case_page.articles') }}
                    </td>
                    <td class="page__cases__case__properties__value">
                        @if($case->articles)
                            @foreach($case->articles as $index => $article)
                                <a
                                    {{--                                href="{{ route('page.cases.all', ['art' => $article]) }}"--}}
                                    class="text-primary">
                                    {{ $case::getArticleName($article) }}</a>@if($index < count($case->articles) - 1)
                                    ,@endif
                            @endforeach
                        @endif
                    </td>
                </tr>
            </table>

            @if($case->page->body['description'] ?? false)
                <div class="page_case__description">
                    <h2 class="text-primary">
                        {{ __('pages.case_page.index.description') }}
                    </h2>
                    <div>
                        {!! $case->page->body['description'] ?? '' !!}
                    </div>
                </div>
            @endif

            @if($case->page->body['threatening'] ?? false)
                <div class="bg-grey-100 mt-12 page_case__threatening">
                    <h2>
                        {{ __('pages.case_page.index.threatening') }}
                    </h2>
                    <div>
                        {!! $case->page->body['threatening'] ?? '' !!}
                    </div>
                </div>
            @endif

            @if($case->page->body['result'] ?? false)
                <div class="mt-12 page_case__result">
                    <h2 class="text-primary">
                        {{ __('pages.case_page.index.result') }}
                    </h2>
                    <div>
                        {!! $case->page->body['result'] ?? '' !!}
                    </div>
                </div>
            @endif

            @if(count($case->getAttachments()) > 0)
                <div class="mt-12 page_case__documents">
                    <h2 class="text-primary">
                        {{ __('pages.case_page.index.documents') }}
                    </h2>
                    <ul class="page_case__documents__carousel">
                        @foreach($case->getAttachments() as $attachment)
                            <li class="flex" data-jbox-image="gallery1">
                                <iframe
                                    @if(app()->environment() == 'local')
                                    src="https://docs.google.com/gview?url=https://steplaw.ru/storage/2022/02/06/e6b6c378969b5a053f27c7360a2ce886d3c64bb4.pdf&embedded=true"
                                    @else
                                    src="https://docs.google.com/gview?url=https://steplaw.ru{{ $attachment['path'] ?? '' }}&embedded=true"
                                    @endif
                                    frameborder="0" class="page_case__documents__preview"></iframe>
                                {{--                                <div class="flex items-center ml-4 page_case__documents__preview__name">--}}
                                {{--                                    {{ $attachment['name'] ?? 'Прикрепленный файл' }}--}}
                                {{--                                </div>--}}
                            </li>
                        @endforeach
                    </ul>
                </div>
            @endif

            @if($case->page->body['review'] ?? false)
                <div class="bg-grey-100 mt-12 page_case__review">
                    @include('partials.blocks.hr.hr_2')
                    <h2 class="text-primary page_case__review__title">
                        {{ __('pages.case_page.index.review') }}
                    </h2>
                    <div class="bg-white px-8 py-10">
                        <h2 class="text-primary page_case__review__name">
                            {{ $case->page->body['review_name'] ?? '' }}
                        </h2>
                        @if($case->page->body['review_date'] ?? false)
                            <p class="text-sm text-grey-400">
                                {{ \Carbon\Carbon::parse($case->page->body['review_date'])->format('d M Y') }}
                            </p>
                        @endif
                        <div>
                            {!! $case->page->body['review'] ?? '' !!}
                        </div>
                    </div>
                </div>
            @endif
        </div>
    </div>

    <section class="container container_small mx-auto bg-white pb-20" id="callback-block">
        <h2 class="text-white mb-6">{{ __('blocks.cases.title') }}</h2>
        @include('partials.blocks.forms.horizontal_2')
    </section>
@endsection

resources/views/pages/contacts.blade.php
@extends('partials.body')

@section('content')
    <section class="page__inner page_contacts">
        <div class="flex flex-wrap container">
            <div class="w-full md:w-2/5 px-6 bg-white overflow-hidden section contacts">
                <h1 class="text-primary text-left">
                    {{ $page->field('title', true) ?? __('pages.contacts.title') }}
                </h1>

                <p class="contacts__name">Адвокатское бюро г. Москвы «Соколов, Трусов и Партнёры»</p>

                <div class="flex flex-wrap contacts__menu">
                    <div class="w-full md:w-1/2 px-1">
                        <p class="text-xl">
                            <strong>{{ __('pages.contacts.phone') }}</strong>
                        </p>
                        <span class="block font-semibold">
                            <a href="tel:{{ \Settings::getPhoneLink('phone_1') }}">
                                {{ \Settings::get('phone_1') }}
                            </a>
                        </span>
                        <span class="block font-semibold mt-1">
                            <a href="tel:{{ \Settings::getPhoneLink('phone_2') }}">
                                {{ \Settings::get('phone_2') }}
                            </a>
                        </span>
                        <p class="text-sm">{{ \Settings::get('duty_lawyer') }}</p>
                    </div>
                    <div class="w-full md:w-1/2 px-1">
                        <p class="text-xl">
                            <strong>{{ __('pages.contacts.email') }}</strong>
                        </p>
                        <p class="font-semibold">
                            <a href="mailto:{{ \Settings::get('email') }}">
                                {{ \Settings::get('email') }}
                            </a>
                        </p>
                    </div>
                    <div class="w-full mt-3 px-1">
                        <p class="text-xl">
                            <strong>{{ __('pages.contacts.address') }}</strong>
                        </p>
                        <p>{{ \Settings::get('address') }}</p>
                    </div>
                    <div class="w-full mt-3 px-1">
                        <p class="text-xl">
                            <strong>{{ __('pages.contacts.work_time') }}</strong>
                        </p>
                        <p>{{ \Settings::get('work_time') }}</p>
                    </div>
                    <div class="w-full mt-3 px-1">
                        <p class="text-xl">
                            <strong>{{ __('pages.contacts.requisites') }}</strong>
                        </p>
                        <p style="white-space: pre-line; margin-bottom: 0;">{{ \Settings::get('requisites') }}</p>
                    </div>
                    <hr>
                    <div class="mt-3 w-full">
                        @include('partials.blocks.forms.form_contacts')
                    </div>
                </div>
            </div>
            <div class="w-full md:w-3/5 contacts__map" id="full-map">
                <iframe
                    src="https://yandex.ru/map-widget/v1/?um=constructor%3Af32e28392b057a9c82b15098cc357fb56815875347728fd2a0ea7727a34315f6&amp;source=constructor"
                    width="100%" height="100%" frameborder="0"></iframe>
            </div>
        </div>
    </section>
@endsection

resources/views/pages/default.blade.php
@extends('partials.body')

@section('content')
    <div class="page__inner page_default">
        <section class="section container container_small bg-white mx-auto">
            @include('partials.blocks.hr.hr_1')
            <h1 class="text-primary">{{ $page->field('title') }}</h1>
            <div class="block__text">
                {!! $page->field('content') !!}
            </div>
        </section>
    </div>
@endsection

resources/views/pages/history.blade.php
@extends('partials.body')

@section('content')
    <div class="page__inner page__history">
        <section class="section container bg-white mx-auto">
            @include('partials.blocks.hr.hr_1')
            <div class="flex justify-center">
                <h1 class="text-primary">{{ $page->field('title') }}</h1>
            </div>
            <div class="block__text">
                {!! $page->field('content') !!}
            </div>

            @if(isset($page->body['steps']) && count($page->body['steps']) > 0)
                <div class="page__history__steps">
                    <ol>
                        @foreach($page->body['steps'] as $step)
                            <li>
                                <div>
                                    <h4>
                                        {{ $step['title'] ?? '' }}
                                    </h4>
                                    {!! $step['content'] ?? '' !!}
                                </div>
                            </li>
                        @endforeach
                    </ol>
                </div>
            @endif
        </section>

        <section class="section container bg-primary mx-auto">
            @include('partials.blocks.hr.hr_1')
            <div class="flex justify-center">
                <p class="text-center text-white font-bold page__history__now">
                    {{ $page->body['comment'] }}
                </p>
            </div>
        </section>

        <section class="section container bg-white mx-auto hidden">
            <div class="flex justify-around page__history__features">
                @foreach($page->body['features'] ?? [] as $feature => $content)
                    <div class="page__history__features__feature">
                        <img class="page__history__features__img"
                             src="/img/features/{{ $feature }}.png" alt="{{ $feature }}">
                        <p class="page__history__features__title">
                            {{ $content['title'] ?? '' }}
                        </p>
                        <div class="page__history__features__content">
                            {!! $content['content'] ?? '' !!}
                        </div>
                    </div>
                @endforeach
            </div>
        </section>

        <section class="container _fw mx-auto persons bg-white overflow-hidden">
            @include('partials.blocks.hr.hr_1')
            <h2 class="text-primary">{{ __('pages.index.persons.title') }}</h2>
            @include('partials.blocks.carousel.persons_small')
        </section>

        @php $certificates = $page->getAttachmentsByArray($page->body['certificates']['files'] ?? []) @endphp
        @if($certificates->count() > 0)
            <section class="container mx-auto bg-white overflow-hidden ds page__history__certificates">
                @include('partials.blocks.hr.hr_1')
                <h2 class="text-primary">{{ $page->body['certificates']['title'] ?? '' }}</h2>
                <div class="mb-10">
                    {!! $page->body['certificates']['text'] ?? '' !!}
                </div>

                <ul class="mb-6 list_unstyled history__files-carousel">
                    @foreach($certificates as $file)
                        <li class="w-full md:w-1/2 xl:w-1/3 px-5 history__files-carousel__item">
                            <a href="{{ $file->url }}" title="{{ $file->title }}" data-jbox-image="certificates">
                                <img src="{{ $file->url }}" alt="{{ $file->title }}">
                            </a>
                        </li>
                    @endforeach
                </ul>

                <div class="splide__arrows text-primary mt-2">
                    <button class="splide__arrow splide__arrow--prev">
                        @include('partials.icons.arrow_rigth')
                    </button>
                    <button class="splide__arrow splide__arrow--next">
                        @include('partials.icons.arrow_rigth')
                    </button>
                </div>
            </section>
        @endif

        <section class="container mx-auto persons bg-white overflow-hidden ds">
            @include('partials.blocks.hr.hr_1')
            <h2 class="text-primary">{{ $page->body['clients']['title'] ?? '' }}</h2>
            <div>
                {!! $page->body['clients']['text'] ?? '' !!}
            </div>
        </section>

        @php $thanks = $page->getAttachmentsByArray($page->body['thanks']['files'] ?? []) @endphp
        @if($thanks)
            <section class="container mx-auto persons bg-white overflow-hidden ds page__history__thanks">
{{--                @include('partials.blocks.hr.hr_1')--}}
{{--                <h2 class="text-primary">{{ __('pages.history.letters.title') }}</h2>--}}

                <ul class="mb-6 list_unstyled history__files-carousel">
                    @foreach($thanks as $file)
                        <li class="w-full md:w-1/2 xl:w-1/3 px-5 history__files-carousel__item">
                            <a href="{{ $file->url }}" title="{{ $file->title }}" data-jbox-image="thanks">
                                <img src="{{ $file->url }}" alt="{{ $file->title }}">
                            </a>
                        </li>
                    @endforeach
                </ul>

                <div class="splide__arrows text-primary mt-2">
                    <button class="splide__arrow splide__arrow--prev">
                        @include('partials.icons.arrow_rigth')
                    </button>
                    <button class="splide__arrow splide__arrow--next">
                        @include('partials.icons.arrow_rigth')
                    </button>
                </div>
            </section>
        @endif

        @php $thanks = \App\Models\Thank::find($page->body['cases'] ?? []) @endphp
        <section class="container mx-auto relative xs-px-0
            bg-white thanks page__history__thanks">
            @include('partials.blocks.hr.hr_1')
            <h2 class="text-primary mb-6">{{ __('pages.history.thanks.title') }}</h2>
            <div>
                <ul class="list_unstyled mb-2 thanks__carousel">
                    @foreach($thanks as $thank)
                        @include('partials.blocks.thanks.thanks_big')
                    @endforeach
                </ul>
                <div class="splide__arrows text-primary mt-2">
                    <button class="splide__arrow splide__arrow--prev">
                        @include('partials.icons.arrow_rigth')
                    </button>
                    <button class="splide__arrow splide__arrow--next">
                        @include('partials.icons.arrow_rigth')
                    </button>
                </div>
            </div>
        </section>

        <section class="container mx-auto bg-white pb-20" id="callback-block">
            <h2 class="text-white mb-6">{{ __('blocks.cases.title') }}</h2>
            @include('partials.blocks.forms.horizontal_2')
        </section>

    </div>
@endsection

resources/views/pages/index.blade.php
@extends('partials.body')

@section('content')
    <section class="bg-grey-100 overflow-hidden advantages">
        <div class="container flex mx-auto relative">
            <div class="absolute left-0 bottom-0 w-full flex z-10">
                <div class="advantages__img advantages__img_1 flex justify-end md:pr-16">
                    <img lazy src="@include('partials.icons.null_image')" data-src="/img/Sokolov_Sait.png"
                         alt="{{ __('pages.index.advantages.persons.sokolov') }}">
                </div>
                <div class="advantages__img advantages__img_2 md:pl-16">
                    <img lazy src="@include('partials.icons.null_image')" data-src="/img/Trusov_Sait.png"
                         alt="{{ __('pages.index.advantages.persons.trusov') }}">
                    <img src="/img/trusov_m_bg_kiborg_real.png"
                         alt="{{ __('pages.index.advantages.persons.trusov') }}"
                         class="absolute top-0 kiborg transition ease-in-out duration-300 opacity-0">
                </div>
            </div>
            <div class="z-20 flex flex-col align-middle text-center relative font-semibold w-full advantages__block">
                <div class="mb-6 advantages__emblem" lazy data-src="/img/emblem.png"></div>
                <p class="text-primary text-3xl md:whitespace-pre-line advantages__title">{{ __('pages.index.advantages.title') }}</p>
                <div class="uppercase mt-6 advantages__items">
                    <span>>5 200</span>
                    <p>{!! __('pages.index.advantages.cases') !!}</p>
                    <span>{{ now()->year - 2005 }}</span>
                    <p>{!! __('pages.index.advantages.work') !!}</p>
                    <span>24/7</span>
                    <p>{!! __('pages.index.advantages.24/7') !!}</p>
                </div>
                <div class="text-xl text-primary advantages__links">
                    <a href="{{ route('page.persons.person', ['person' => 'sokolov-andrey-nikolaevich.html']) }}"
                       class="border-b-2 border-primary leading-1 advantages__links_1">
                        {{ __('pages.index.advantages.persons.sokolov') }}
                    </a>
                    <a href="{{ route('page.persons.person', ['person' => 'trusov-fedor-nikolaevich.html']) }}"
                       class="border-b-2 border-primary leading-1 advantages__links_2">
                        {{ __('pages.index.advantages.persons.trusov') }}
                    </a>
                </div>
            </div>
        </div>
    </section>

    <section class="bg-primary text-white py-6 section services__wrap">
        <div class="container">
            @include('partials.blocks.hr.hr_1')
            <h2>{{ __('pages.index.services.title') }}</h2>
            @include('partials.blocks.services.services')
        </div>
    </section>

    <section class="bg-grey-100 section persons">
        <div class="container mx-auto relative">
            @include('partials.blocks.hr.hr_1')
            <h2 class="text-primary">{{ __('pages.index.persons.title') }}</h2>
            @include('partials.blocks.carousel.persons')
        </div>
    </section>

    @if($cases->count() > 0)
        <section class="section cases">
            <div class="container mx-auto relative xs-px-0">
                @include('partials.blocks.hr.hr_1')
                <h2 class="text-primary mb-6">{{ __('pages.index.cases.title') }}</h2>
                @include('partials.blocks.cases.cases')
            </div>
        </section>
    @endif

    <section class="bg-grey-100 section thanks">
        <div class="container mx-auto relative xs-px-0">
            @include('partials.blocks.hr.hr_1')
            <h2 class="text-primary mb-6">{{ __('pages.index.thanks.title') }}</h2>
            @include('partials.blocks.carousel.thanks', ['count' => 2])
        </div>
    </section>

    <section class="section partner" id="moment">
        <div class="container mx-auto relative text-white md:px-6">
            @include('partials.blocks.hr.hr_1')
            <h2 class="mb-5">{{ __('pages.index.partners.title') }}</h2>
            <p class="font-semibold mb-12">{{ __('pages.index.partners.description') }}</p>
            @include('partials.blocks.carousel.partner')
        </div>
    </section>

    <section class="bg-grey-100 section mentioning" id="smi">
        <div class="container mx-auto relative">
            @include('partials.blocks.hr.hr_1')
            <h2 class="text-primary mb-4">{{ __('pages.index.mentioning.title') }}</h2>
            @include('partials.blocks.mentioning.mentioning')
        </div>
    </section>

    <section class="section">
        <div class="container mx-auto relative">
            @include('partials.blocks.hr.hr_1')
            <h1 class="text-primary mb-6">{{ $page->field('title') }}</h1>
            <div class="page__inner block__text">
                @php $cols = explode('<p><!-- pagebreak --></p>',$page->field('content')); @endphp
                @include('partials.blocks.texts.2', [
                    'col_1' => $cols[0] ?? '',
                    'col_2' => $cols[1] ?? '',
                ])
            </div>
        </div>
    </section>

    <section class="bg-grey-100 section" id="callback">
        <div class="container mx-auto">
            @include('partials.blocks.forms.horizontal_1')
        </div>
    </section>
@endsection

resources/views/pages/pay.blade.php
@extends('partials.body')

@section('content')
    <div class="section page__pay">
        <div class="container">
            <h1>{{ __('pages.payment.pay.title') }}</h1>

            <div class="flex flex-col items-center">
                <p class="text-grey-500 text-xl text-center">
                    {!! __('pages.payment.pay.subtitle') !!}
                </p>
                <img src="/spb_qr.svg?v=2.1" style="max-width: 400px;">
            </div>

        </div>
    </div>
@endsection

resources/views/pages/persons.blade.php
@extends('partials.body')

@section('content')

    <div class="container container_small">
        @include('partials.blocks.breadcrumbs.breadcrumbs')
    </div>
    
    <section class="container section page_persons">
        @include('partials.blocks.hr.hr_1')
        <h1 class="text-primary">
            {{ $page->field('title', true) ?? __('pages.index.persons.title') }}
        </h1>
        <div class="{{ !\Agent::isMobile() ? 'flex' : '' }}">
            @if(!\Agent::isMobile())
                <div class="w-1/6"></div>
            @endif
            <div class="{{ \Agent::isMobile() ? '' : 'w-4/6' }} mb-10 persons__carousel disable_carousel flex flex-wrap">
                @foreach($persons as $i => $person)
                    <div class="w-full md:w-1/3 py-3 md:py-5">
                        @include('partials.blocks.persons.person_item')
                    </div>
                @endforeach
            </div>
        </div>
    </section>
    <section class="bg-grey-100 section">
        <div class="container mx-auto">
            @include('partials.blocks.forms.horizontal_1')
        </div>
    </section>
@endsection

resources/views/pages/questions.blade.php
@extends('partials.body')

@section('content')
    <div class="section page__cases page__questions">
        <div class="container">
            <h1>
                {{ __('pages.questions.list.title') }}
            </h1>

            <div class="case-categories__carousel page__cases__categories">
                @foreach($services as $i => $service)
{{--                    <a href="{{ route('page.qa.all', ['service' => $service->id]) }}" class="case">--}}
                    <a class="case" data-service-id="{{ $service->id }}">
                        {{ $service->name }}
                    </a>
                @endforeach
            </div>

            <p class="page__cases__total">
                {{ __('pages.case_page.list.total', ['count' => $items->total()]) }}
            </p>

            @include('pages.partials.faqs', ['items' => $items])

            {!! $items->links() !!}
        </div>
    </div>
@endsection

resources/views/pages/verification.blade.php
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
</head>
<body>Verification: 130936c9dc22b6e7</body>
</html>